//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Roles> tbl_Roles { get; set; }
        public virtual DbSet<tbl_RolesUsuarios> tbl_RolesUsuarios { get; set; }
        public virtual DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public virtual DbSet<tbl_Alumno> tbl_Alumno { get; set; }
        public virtual DbSet<tbl_AlumnoAlergia> tbl_AlumnoAlergia { get; set; }
        public virtual DbSet<tbl_AlumnoApoderado> tbl_AlumnoApoderado { get; set; }
        public virtual DbSet<tbl_AlumnoDiscapacidad> tbl_AlumnoDiscapacidad { get; set; }
        public virtual DbSet<tbl_AnioEscolar> tbl_AnioEscolar { get; set; }
        public virtual DbSet<tbl_Apoderado> tbl_Apoderado { get; set; }
        public virtual DbSet<tbl_Asignatura> tbl_Asignatura { get; set; }
        public virtual DbSet<tbl_CatalogoAlergia> tbl_CatalogoAlergia { get; set; }
        public virtual DbSet<tbl_CausalRetiro> tbl_CausalRetiro { get; set; }
        public virtual DbSet<tbl_Comuna> tbl_Comuna { get; set; }
        public virtual DbSet<tbl_CondicionSocioeconomica> tbl_CondicionSocioeconomica { get; set; }
        public virtual DbSet<tbl_ContactoEmergencia> tbl_ContactoEmergencia { get; set; }
        public virtual DbSet<tbl_Curso> tbl_Curso { get; set; }
        public virtual DbSet<tbl_CursoAsignatura> tbl_CursoAsignatura { get; set; }
        public virtual DbSet<tbl_DocumentoAlumno> tbl_DocumentoAlumno { get; set; }
        public virtual DbSet<tbl_Establecimiento> tbl_Establecimiento { get; set; }
        public virtual DbSet<tbl_EstadoAlumno> tbl_EstadoAlumno { get; set; }
        public virtual DbSet<tbl_EstadoMatricula> tbl_EstadoMatricula { get; set; }
        public virtual DbSet<tbl_EstadoProfesor> tbl_EstadoProfesor { get; set; }
        public virtual DbSet<tbl_Etnia> tbl_Etnia { get; set; }
        public virtual DbSet<tbl_FirmanteCertificado> tbl_FirmanteCertificado { get; set; }
        public virtual DbSet<tbl_Grado> tbl_Grado { get; set; }
        public virtual DbSet<tbl_LogActividad> tbl_LogActividad { get; set; }
        public virtual DbSet<tbl_Matricula> tbl_Matricula { get; set; }
        public virtual DbSet<tbl_Nacionalidad> tbl_Nacionalidad { get; set; }
        public virtual DbSet<tbl_NivelEducacional> tbl_NivelEducacional { get; set; }
        public virtual DbSet<tbl_NivelEnsenanza> tbl_NivelEnsenanza { get; set; }
        public virtual DbSet<tbl_Nota> tbl_Nota { get; set; }
        public virtual DbSet<tbl_Parentesco> tbl_Parentesco { get; set; }
        public virtual DbSet<tbl_PIE> tbl_PIE { get; set; }
        public virtual DbSet<tbl_PlantillaCertificado> tbl_PlantillaCertificado { get; set; }
        public virtual DbSet<tbl_ProfesorJefe> tbl_ProfesorJefe { get; set; }
        public virtual DbSet<tbl_Region> tbl_Region { get; set; }
        public virtual DbSet<tbl_RetiroAlumno> tbl_RetiroAlumno { get; set; }
        public virtual DbSet<tbl_Sexo> tbl_Sexo { get; set; }
        public virtual DbSet<tbl_SistemaSalud> tbl_SistemaSalud { get; set; }
        public virtual DbSet<tbl_SituacionLaboral> tbl_SituacionLaboral { get; set; }
        public virtual DbSet<tbl_TipoAlergia> tbl_TipoAlergia { get; set; }
        public virtual DbSet<tbl_TipoDiscapacidad> tbl_TipoDiscapacidad { get; set; }
        public virtual DbSet<tbl_TipoDocumento> tbl_TipoDocumento { get; set; }
        public virtual DbSet<tbl_TraspasoRut> tbl_TraspasoRut { get; set; }
        public virtual DbSet<tbl_ViveCon> tbl_ViveCon { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_ProcesoAnualPromocion(Nullable<int> anioEscolarOrigenID, Nullable<int> anioEscolarDestinoID, string createdBy)
        {
            var anioEscolarOrigenIDParameter = anioEscolarOrigenID.HasValue ?
                new ObjectParameter("AnioEscolarOrigenID", anioEscolarOrigenID) :
                new ObjectParameter("AnioEscolarOrigenID", typeof(int));
    
            var anioEscolarDestinoIDParameter = anioEscolarDestinoID.HasValue ?
                new ObjectParameter("AnioEscolarDestinoID", anioEscolarDestinoID) :
                new ObjectParameter("AnioEscolarDestinoID", typeof(int));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_ProcesoAnualPromocion", anioEscolarOrigenIDParameter, anioEscolarDestinoIDParameter, createdByParameter);
        }
    }
}
