//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TipoDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_TipoDocumento()
        {
            this.tbl_DocumentoAlumno = new HashSet<tbl_DocumentoAlumno>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public bool Obligatorio { get; set; }
        public bool IsActive { get; set; }
        public bool EsAnexo { get; set; }
        public string Categoria { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DocumentoAlumno> tbl_DocumentoAlumno { get; set; }
    }
}
