//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Grado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Grado()
        {
            this.tbl_Curso = new HashSet<tbl_Curso>();
        }
    
        public int ID { get; set; }
        public int NivelEnsenanzaID { get; set; }
        public string Nombre { get; set; }
        public int Orden { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Curso> tbl_Curso { get; set; }
        public virtual tbl_NivelEnsenanza tbl_NivelEnsenanza { get; set; }
    }
}
