//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TraspasoRut
    {
        public int ID { get; set; }
        public int AlumnoOrigenID { get; set; }
        public int AlumnoDestinoID { get; set; }
        public string RutAnterior { get; set; }
        public string RutNuevo { get; set; }
        public System.DateTime FechaTraspaso { get; set; }
        public string Motivo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_Alumno tbl_Alumno { get; set; }
        public virtual tbl_Alumno tbl_Alumno1 { get; set; }
    }
}
