//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CatalogoAlergia
    {
        public int ID { get; set; }
        public int TipoAlergiaID { get; set; }
        public string Nombre { get; set; }
        public bool RequiereDetalle { get; set; }
        public int Orden { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_TipoAlergia tbl_TipoAlergia { get; set; }
    }
}
