//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Alumno()
        {
            this.tbl_Alumno1 = new HashSet<tbl_Alumno>();
            this.tbl_AlumnoDiscapacidad = new HashSet<tbl_AlumnoDiscapacidad>();
            this.tbl_TraspasoRut = new HashSet<tbl_TraspasoRut>();
            this.tbl_TraspasoRut1 = new HashSet<tbl_TraspasoRut>();
            this.tbl_AlumnoApoderado = new HashSet<tbl_AlumnoApoderado>();
            this.tbl_AlumnoAlergia = new HashSet<tbl_AlumnoAlergia>();
            this.tbl_ContactoEmergencia = new HashSet<tbl_ContactoEmergencia>();
            this.tbl_DocumentoAlumno = new HashSet<tbl_DocumentoAlumno>();
            this.tbl_Matricula = new HashSet<tbl_Matricula>();
            this.tbl_PIE = new HashSet<tbl_PIE>();
            this.tbl_RetiroAlumno = new HashSet<tbl_RetiroAlumno>();
        }
    
        public int ID { get; set; }
        public string Rut { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> SexoID { get; set; }
        public Nullable<int> NacionalidadID { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> ComunaID { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> SistemaSaludID { get; set; }
        public bool TieneDiscapacidad { get; set; }
        public bool TienePIE { get; set; }
        public int EstadoAlumnoID { get; set; }
        public Nullable<System.DateTime> FotoCargada { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<int> EtniaID { get; set; }
        public Nullable<int> CondicionSocioeconomicaID { get; set; }
        public Nullable<int> ViveConID { get; set; }
        public Nullable<int> AlumnoOrigenID { get; set; }
        public string RutAnterior { get; set; }
        public byte[] FotoContenido { get; set; }
        public string FotoMimeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Alumno> tbl_Alumno1 { get; set; }
        public virtual tbl_Alumno tbl_Alumno2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AlumnoDiscapacidad> tbl_AlumnoDiscapacidad { get; set; }
        public virtual tbl_CondicionSocioeconomica tbl_CondicionSocioeconomica { get; set; }
        public virtual tbl_Etnia tbl_Etnia { get; set; }
        public virtual tbl_ViveCon tbl_ViveCon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TraspasoRut> tbl_TraspasoRut { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_TraspasoRut> tbl_TraspasoRut1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AlumnoApoderado> tbl_AlumnoApoderado { get; set; }
        public virtual tbl_Comuna tbl_Comuna { get; set; }
        public virtual tbl_EstadoAlumno tbl_EstadoAlumno { get; set; }
        public virtual tbl_Nacionalidad tbl_Nacionalidad { get; set; }
        public virtual tbl_SistemaSalud tbl_SistemaSalud { get; set; }
        public virtual tbl_Sexo tbl_Sexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AlumnoAlergia> tbl_AlumnoAlergia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ContactoEmergencia> tbl_ContactoEmergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DocumentoAlumno> tbl_DocumentoAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Matricula> tbl_Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PIE> tbl_PIE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_RetiroAlumno> tbl_RetiroAlumno { get; set; }
    }
}
