//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Nota
    {
        public int ID { get; set; }
        public int MatriculaID { get; set; }
        public int CursoAsignaturaID { get; set; }
        public string Periodo { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public string Tipo { get; set; }
        public string Observacion { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_CursoAsignatura tbl_CursoAsignatura { get; set; }
        public virtual tbl_Matricula tbl_Matricula { get; set; }
    }
}
