//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Matricula()
        {
            this.tbl_Nota = new HashSet<tbl_Nota>();
        }
    
        public int ID { get; set; }
        public int AlumnoID { get; set; }
        public int CursoID { get; set; }
        public int AnioEscolarID { get; set; }
        public string NroMatricula { get; set; }
        public System.DateTime FechaMatricula { get; set; }
        public int EstadoMatriculaID { get; set; }
        public string Observacion { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public bool EsAlumnoNuevo { get; set; }
        public string NroMatriculaAnterior { get; set; }
        public string ResultadoPromocion { get; set; }
        public bool MatriculaCancelada { get; set; }
        public string MotivoNoPromocion { get; set; }
        public string DecretoNoPromocion { get; set; }
        public string GlosaNoPromocion { get; set; }
        public Nullable<System.DateTime> FechaResultadoPromocion { get; set; }
    
        public virtual tbl_Alumno tbl_Alumno { get; set; }
        public virtual tbl_AnioEscolar tbl_AnioEscolar { get; set; }
        public virtual tbl_Curso tbl_Curso { get; set; }
        public virtual tbl_EstadoMatricula tbl_EstadoMatricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Nota> tbl_Nota { get; set; }
    }
}
