//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Apoderado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Apoderado()
        {
            this.tbl_AlumnoApoderado = new HashSet<tbl_AlumnoApoderado>();
        }
    
        public int ID { get; set; }
        public string Rut { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public Nullable<int> NacionalidadID { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> ComunaID { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<int> NivelEducacionalID { get; set; }
        public Nullable<int> SituacionLaboralID { get; set; }
        public string LugarTrabajo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string TelefonoCelular { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AlumnoApoderado> tbl_AlumnoApoderado { get; set; }
        public virtual tbl_Comuna tbl_Comuna { get; set; }
        public virtual tbl_Nacionalidad tbl_Nacionalidad { get; set; }
        public virtual tbl_NivelEducacional tbl_NivelEducacional { get; set; }
        public virtual tbl_SituacionLaboral tbl_SituacionLaboral { get; set; }
    }
}
