//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AlumnoApoderado
    {
        public int ID { get; set; }
        public int AlumnoID { get; set; }
        public int ApoderadoID { get; set; }
        public int ParentescoID { get; set; }
        public bool EsApoderadoTitular { get; set; }
        public bool EsPadre { get; set; }
        public bool EsMadre { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_Alumno tbl_Alumno { get; set; }
        public virtual tbl_Apoderado tbl_Apoderado { get; set; }
        public virtual tbl_Parentesco tbl_Parentesco { get; set; }
    }
}
