//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_AnioEscolar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_AnioEscolar()
        {
            this.tbl_Curso = new HashSet<tbl_Curso>();
            this.tbl_DocumentoAlumno = new HashSet<tbl_DocumentoAlumno>();
            this.tbl_Matricula = new HashSet<tbl_Matricula>();
            this.tbl_PIE = new HashSet<tbl_PIE>();
        }
    
        public int ID { get; set; }
        public int EstablecimientoID { get; set; }
        public int Anio { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
        public bool Cerrado { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public bool EsActivo { get; set; }
    
        public virtual tbl_Establecimiento tbl_Establecimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Curso> tbl_Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_DocumentoAlumno> tbl_DocumentoAlumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Matricula> tbl_Matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_PIE> tbl_PIE { get; set; }
    }
}
