//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_LogActividad
    {
        public int ID { get; set; }
        public string Entidad { get; set; }
        public int EntidadID { get; set; }
        public string Accion { get; set; }
        public string Usuario { get; set; }
        public System.DateTime FechaAccion { get; set; }
        public string Detalle { get; set; }
    }
}
