//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DocumentoAlumno
    {
        public int ID { get; set; }
        public int AlumnoID { get; set; }
        public int TipoDocumentoID { get; set; }
        public string NombreArchivo { get; set; }
        public System.DateTime FechaCarga { get; set; }
        public string Observacion { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> AnioEscolarID { get; set; }
        public byte[] Contenido { get; set; }
        public string MimeType { get; set; }
    
        public virtual tbl_Alumno tbl_Alumno { get; set; }
        public virtual tbl_AnioEscolar tbl_AnioEscolar { get; set; }
        public virtual tbl_TipoDocumento tbl_TipoDocumento { get; set; }
    }
}
