//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Establecimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Establecimiento()
        {
            this.tbl_AnioEscolar = new HashSet<tbl_AnioEscolar>();
        }
    
        public int ID { get; set; }
        public string RBD { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> ComunaID { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string Ciudad { get; set; }
        public string SitioWeb { get; set; }
        public byte[] Logo { get; set; }
        public string LogoMimeType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AnioEscolar> tbl_AnioEscolar { get; set; }
        public virtual tbl_Comuna tbl_Comuna { get; set; }
    }
}
