//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comuna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Comuna()
        {
            this.tbl_Alumno = new HashSet<tbl_Alumno>();
            this.tbl_Apoderado = new HashSet<tbl_Apoderado>();
            this.tbl_Establecimiento = new HashSet<tbl_Establecimiento>();
        }
    
        public int ID { get; set; }
        public int RegionID { get; set; }
        public string Nombre { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Alumno> tbl_Alumno { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Apoderado> tbl_Apoderado { get; set; }
        public virtual tbl_Region tbl_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Establecimiento> tbl_Establecimiento { get; set; }
    }
}
