//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Curso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Curso()
        {
            this.tbl_CursoAsignatura = new HashSet<tbl_CursoAsignatura>();
            this.tbl_Matricula = new HashSet<tbl_Matricula>();
        }
    
        public int ID { get; set; }
        public int AnioEscolarID { get; set; }
        public int GradoID { get; set; }
        public string Letra { get; set; }
        public Nullable<int> Capacidad { get; set; }
        public Nullable<int> ProfesorJefeID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_AnioEscolar tbl_AnioEscolar { get; set; }
        public virtual tbl_Grado tbl_Grado { get; set; }
        public virtual tbl_ProfesorJefe tbl_ProfesorJefe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_CursoAsignatura> tbl_CursoAsignatura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Matricula> tbl_Matricula { get; set; }
    }
}
