//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PIE
    {
        public int ID { get; set; }
        public int AlumnoID { get; set; }
        public int AnioEscolarID { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<int> ProfesionalID { get; set; }
        public string Observacion { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual tbl_Alumno tbl_Alumno { get; set; }
        public virtual tbl_AnioEscolar tbl_AnioEscolar { get; set; }
    }
}
