//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionColegios.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CursoAsignatura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_CursoAsignatura()
        {
            this.tbl_Nota = new HashSet<tbl_Nota>();
        }
    
        public int ID { get; set; }
        public int CursoID { get; set; }
        public int AsignaturaID { get; set; }
        public Nullable<int> HorasSemana { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_Asignatura tbl_Asignatura { get; set; }
        public virtual tbl_Curso tbl_Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Nota> tbl_Nota { get; set; }
    }
}
