//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public DbSet<tbl_Bancos> tbl_Bancos { get; set; }
        public DbSet<tbl_Categorias> tbl_Categorias { get; set; }
        public DbSet<tbl_Causas> tbl_Causas { get; set; }
        public DbSet<tbl_Cementerios> tbl_Cementerios { get; set; }
        public DbSet<tbl_Comunas> tbl_Comunas { get; set; }
        public DbSet<tbl_Conceptos> tbl_Conceptos { get; set; }
        public DbSet<tbl_ConceptosServicios> tbl_ConceptosServicios { get; set; }
        public DbSet<tbl_Difuntos> tbl_Difuntos { get; set; }
        public DbSet<tbl_Estados> tbl_Estados { get; set; }
        public DbSet<tbl_FormasPago> tbl_FormasPago { get; set; }
        public DbSet<tbl_HistorialAdquisicion> tbl_HistorialAdquisicion { get; set; }
        public DbSet<tbl_Letra> tbl_Letra { get; set; }
        public DbSet<tbl_LugarDefuncion> tbl_LugarDefuncion { get; set; }
        public DbSet<tbl_Observaciones> tbl_Observaciones { get; set; }
        public DbSet<tbl_PagoAdquisicion> tbl_PagoAdquisicion { get; set; }
        public DbSet<tbl_PagosMantenciones> tbl_PagosMantenciones { get; set; }
        public DbSet<tbl_Parrocos> tbl_Parrocos { get; set; }
        public DbSet<tbl_Patios> tbl_Patios { get; set; }
        public DbSet<tbl_Regiones> tbl_Regiones { get; set; }
        public DbSet<tbl_Roles> tbl_Roles { get; set; }
        public DbSet<tbl_RolesUsuarios> tbl_RolesUsuarios { get; set; }
        public DbSet<tbl_SeccionConceptos> tbl_SeccionConceptos { get; set; }
        public DbSet<tbl_Secciones> tbl_Secciones { get; set; }
        public DbSet<tbl_Servicios> tbl_Servicios { get; set; }
        public DbSet<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
        public DbSet<tbl_TipoAdministrador> tbl_TipoAdministrador { get; set; }
        public DbSet<tbl_TipoMonedas> tbl_TipoMonedas { get; set; }
        public DbSet<tbl_Usuarios> tbl_Usuarios { get; set; }
        public DbSet<tbl_ValorMonedas> tbl_ValorMonedas { get; set; }
        public DbSet<tbl_Maestros> tbl_Maestros { get; set; }
    }
}
