//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TipoMonedas
    {
        public tbl_TipoMonedas()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
            this.tbl_ConceptosServicios = new HashSet<tbl_ConceptosServicios>();
            this.tbl_PagosMantenciones = new HashSet<tbl_PagosMantenciones>();
            this.tbl_SeccionConceptos = new HashSet<tbl_SeccionConceptos>();
            this.tbl_ServiciosAdquisicion = new HashSet<tbl_ServiciosAdquisicion>();
            this.tbl_ValorMonedas = new HashSet<tbl_ValorMonedas>();
        }
    
        public int ID { get; set; }
        public string TipoMoneda { get; set; }
        public bool IsActive { get; set; }
        public string Periodicidad { get; set; }
        public bool HasSymbol { get; set; }
        public string Format { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public virtual ICollection<tbl_ConceptosServicios> tbl_ConceptosServicios { get; set; }
        public virtual ICollection<tbl_PagosMantenciones> tbl_PagosMantenciones { get; set; }
        public virtual ICollection<tbl_SeccionConceptos> tbl_SeccionConceptos { get; set; }
        public virtual ICollection<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
        public virtual ICollection<tbl_ValorMonedas> tbl_ValorMonedas { get; set; }
    }
}
