//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Parrocos
    {
        public int ID { get; set; }
        public string NombreParroco { get; set; }
        public string RutParroco { get; set; }
        public bool IsActive { get; set; }
        public int TipoAdministradorID { get; set; }
    
        public virtual tbl_TipoAdministrador tbl_TipoAdministrador { get; set; }
    }
}
