//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Roles
    {
        public tbl_Roles()
        {
            this.tbl_RolesUsuarios = new HashSet<tbl_RolesUsuarios>();
        }
    
        public int ID { get; set; }
        public string Rol { get; set; }
    
        public virtual ICollection<tbl_RolesUsuarios> tbl_RolesUsuarios { get; set; }
    }
}
