//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Adquisicion
    {
        public tbl_Adquisicion()
        {
            this.tbl_Adquisicion1 = new HashSet<tbl_Adquisicion>();
            this.tbl_Adquisicion11 = new HashSet<tbl_Adquisicion>();
            this.tbl_Difuntos = new HashSet<tbl_Difuntos>();
            this.tbl_HistorialAdquisicion = new HashSet<tbl_HistorialAdquisicion>();
            this.tbl_Observaciones = new HashSet<tbl_Observaciones>();
            this.tbl_PagoAdquisicion = new HashSet<tbl_PagoAdquisicion>();
            this.tbl_PagosMantenciones = new HashSet<tbl_PagosMantenciones>();
            this.tbl_ServiciosAdquisicion = new HashSet<tbl_ServiciosAdquisicion>();
        }
    
        public int ID { get; set; }
        public string NroFicha { get; set; }
        public int CementerioID { get; set; }
        public string CompRut { get; set; }
        public string CompNombre { get; set; }
        public string CompApellido { get; set; }
        public int CompComunaID { get; set; }
        public string CompDireccion { get; set; }
        public string CompNum { get; set; }
        public string CompTelefono { get; set; }
        public string CompEmail { get; set; }
        public string RefRut { get; set; }
        public string RefNombre { get; set; }
        public string RefApellido { get; set; }
        public int RefComunaID { get; set; }
        public string RefDireccion { get; set; }
        public string RefNum { get; set; }
        public string RefTelefono { get; set; }
        public string RefEmail { get; set; }
        public int UbiSectorID { get; set; }
        public string UbiNumero { get; set; }
        public int ProductoID { get; set; }
        public string Producto { get; set; }
        public decimal PrecioProducto { get; set; }
        public string LetraNicho { get; set; }
        public System.DateTime FechaAdquisicion { get; set; }
        public int UsuarioID { get; set; }
        public int EstadoID { get; set; }
        public bool IsTrasferred { get; set; }
        public Nullable<int> TranferredID { get; set; }
        public string TransferredNroFicha { get; set; }
        public Nullable<int> NextTransferID { get; set; }
        public string NextTransferNroFicha { get; set; }
        public bool IsRegulated { get; set; }
        public int TipoMonedaID { get; set; }
        public Nullable<decimal> ValorTipoMonedaActual { get; set; }
        public Nullable<decimal> PrecioTipoMoneda { get; set; }
        public Nullable<System.DateTime> FechaTipoMoneda { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion1 { get; set; }
        public virtual tbl_Adquisicion tbl_Adquisicion2 { get; set; }
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion11 { get; set; }
        public virtual tbl_Adquisicion tbl_Adquisicion3 { get; set; }
        public virtual tbl_Cementerios tbl_Cementerios { get; set; }
        public virtual tbl_Comunas tbl_Comunas { get; set; }
        public virtual tbl_Comunas tbl_Comunas1 { get; set; }
        public virtual tbl_Conceptos tbl_Conceptos { get; set; }
        public virtual tbl_Estados tbl_Estados { get; set; }
        public virtual tbl_Secciones tbl_Secciones { get; set; }
        public virtual tbl_TipoMonedas tbl_TipoMonedas { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
        public virtual ICollection<tbl_Difuntos> tbl_Difuntos { get; set; }
        public virtual ICollection<tbl_HistorialAdquisicion> tbl_HistorialAdquisicion { get; set; }
        public virtual ICollection<tbl_Observaciones> tbl_Observaciones { get; set; }
        public virtual ICollection<tbl_PagoAdquisicion> tbl_PagoAdquisicion { get; set; }
        public virtual ICollection<tbl_PagosMantenciones> tbl_PagosMantenciones { get; set; }
        public virtual ICollection<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
    }
}
