//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Estados
    {
        public tbl_Estados()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
        }
    
        public int ID { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
    }
}
