//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Difuntos
    {
        public int ID { get; set; }
        public string Rut { get; set; }
        public string NombreApellido { get; set; }
        public int Edad { get; set; }
        public System.DateTime FechaDefuncion { get; set; }
        public int CausaID { get; set; }
        public int AdquisicionID { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<bool> Reuso { get; set; }
        public Nullable<System.DateTime> FechaReuso { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public bool IsActive { get; set; }
        public int LugarID { get; set; }
    
        public virtual tbl_Adquisicion tbl_Adquisicion { get; set; }
        public virtual tbl_Causas tbl_Causas { get; set; }
        public virtual tbl_LugarDefuncion tbl_LugarDefuncion { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
