//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ConceptosServicios
    {
        public int ID { get; set; }
        public int SeccionID { get; set; }
        public int ServicioID { get; set; }
        public int ConceptoID { get; set; }
        public bool IsActive { get; set; }
        public decimal Precio { get; set; }
        public int TipoMonedaID { get; set; }
    
        public virtual tbl_Conceptos tbl_Conceptos { get; set; }
        public virtual tbl_Secciones tbl_Secciones { get; set; }
        public virtual tbl_Servicios tbl_Servicios { get; set; }
        public virtual tbl_TipoMonedas tbl_TipoMonedas { get; set; }
    }
}
