//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TipoAdministrador
    {
        public tbl_TipoAdministrador()
        {
            this.tbl_Parrocos = new HashSet<tbl_Parrocos>();
        }
    
        public int ID { get; set; }
        public string TipoAdministrador { get; set; }
    
        public virtual ICollection<tbl_Parrocos> tbl_Parrocos { get; set; }
    }
}
