//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cementerios
    {
        public tbl_Cementerios()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
            this.tbl_Patios = new HashSet<tbl_Patios>();
        }
    
        public int ID { get; set; }
        public string Cementerio { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public virtual ICollection<tbl_Patios> tbl_Patios { get; set; }
    }
}
