//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Maestros
    {
        public tbl_Maestros()
        {
            this.tbl_ServiciosAdquisicion = new HashSet<tbl_ServiciosAdquisicion>();
        }
    
        public int ID { get; set; }
        public string Rut { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int ComunaID { get; set; }
        public string Direccion { get; set; }
        public string Num { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tbl_Comunas tbl_Comunas { get; set; }
        public virtual ICollection<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
    }
}
