//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ValorMonedas
    {
        public int ID { get; set; }
        public int Dia { get; set; }
        public int Mes { get; set; }
        public int Year { get; set; }
        public decimal Valor { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int TipoMonedaID { get; set; }
    
        public virtual tbl_TipoMonedas tbl_TipoMonedas { get; set; }
    }
}
