//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Conceptos
    {
        public tbl_Conceptos()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
            this.tbl_ConceptosServicios = new HashSet<tbl_ConceptosServicios>();
            this.tbl_SeccionConceptos = new HashSet<tbl_SeccionConceptos>();
        }
    
        public int ID { get; set; }
        public string Concepto { get; set; }
        public bool IsActive { get; set; }
        public int CategoriaID { get; set; }
        public bool IsNicho { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public virtual tbl_Categorias tbl_Categorias { get; set; }
        public virtual ICollection<tbl_ConceptosServicios> tbl_ConceptosServicios { get; set; }
        public virtual ICollection<tbl_SeccionConceptos> tbl_SeccionConceptos { get; set; }
    }
}
