//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PagosMantenciones
    {
        public int ID { get; set; }
        public int MantencionID { get; set; }
        public decimal Precio { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioID { get; set; }
        public int AdquisicionID { get; set; }
        public int Anio { get; set; }
        public string Observacion { get; set; }
        public int TipoMonedaID { get; set; }
        public Nullable<decimal> ValorTipoMonedaActual { get; set; }
        public Nullable<decimal> PrecioTipoMoneda { get; set; }
        public Nullable<System.DateTime> FechaTipoMoneda { get; set; }
    
        public virtual tbl_Adquisicion tbl_Adquisicion { get; set; }
        public virtual tbl_Servicios tbl_Servicios { get; set; }
        public virtual tbl_TipoMonedas tbl_TipoMonedas { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
