//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Comunas
    {
        public tbl_Comunas()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
            this.tbl_Adquisicion1 = new HashSet<tbl_Adquisicion>();
            this.tbl_Maestros = new HashSet<tbl_Maestros>();
        }
    
        public int ID { get; set; }
        public string Comuna { get; set; }
        public bool IsActive { get; set; }
        public int RegionID { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion1 { get; set; }
        public virtual tbl_Regiones tbl_Regiones { get; set; }
        public virtual ICollection<tbl_Maestros> tbl_Maestros { get; set; }
    }
}
