//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Regiones
    {
        public tbl_Regiones()
        {
            this.tbl_Comunas = new HashSet<tbl_Comunas>();
        }
    
        public int ID { get; set; }
        public int NroRegion { get; set; }
        public string Simbologia { get; set; }
        public string Region { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tbl_Comunas> tbl_Comunas { get; set; }
    }
}
