//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Usuarios
    {
        public tbl_Usuarios()
        {
            this.tbl_Adquisicion = new HashSet<tbl_Adquisicion>();
            this.tbl_Difuntos = new HashSet<tbl_Difuntos>();
            this.tbl_HistorialAdquisicion = new HashSet<tbl_HistorialAdquisicion>();
            this.tbl_Observaciones = new HashSet<tbl_Observaciones>();
            this.tbl_PagosMantenciones = new HashSet<tbl_PagosMantenciones>();
            this.tbl_RolesUsuarios = new HashSet<tbl_RolesUsuarios>();
            this.tbl_ServiciosAdquisicion = new HashSet<tbl_ServiciosAdquisicion>();
        }
    
        public int ID { get; set; }
        public string Username { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public System.DateTime Creado { get; set; }
        public bool IsActive { get; set; }
        public bool IsSuperAdmin { get; set; }
        public string TokenHash { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual ICollection<tbl_Adquisicion> tbl_Adquisicion { get; set; }
        public virtual ICollection<tbl_Difuntos> tbl_Difuntos { get; set; }
        public virtual ICollection<tbl_HistorialAdquisicion> tbl_HistorialAdquisicion { get; set; }
        public virtual ICollection<tbl_Observaciones> tbl_Observaciones { get; set; }
        public virtual ICollection<tbl_PagosMantenciones> tbl_PagosMantenciones { get; set; }
        public virtual ICollection<tbl_RolesUsuarios> tbl_RolesUsuarios { get; set; }
        public virtual ICollection<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
    }
}
