//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Categorias
    {
        public tbl_Categorias()
        {
            this.tbl_Conceptos = new HashSet<tbl_Conceptos>();
            this.tbl_Servicios = new HashSet<tbl_Servicios>();
        }
    
        public int ID { get; set; }
        public string Categoria { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tbl_Conceptos> tbl_Conceptos { get; set; }
        public virtual ICollection<tbl_Servicios> tbl_Servicios { get; set; }
    }
}
