//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Bancos
    {
        public tbl_Bancos()
        {
            this.tbl_PagoAdquisicion = new HashSet<tbl_PagoAdquisicion>();
        }
    
        public int ID { get; set; }
        public string Banco { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tbl_PagoAdquisicion> tbl_PagoAdquisicion { get; set; }
    }
}
