//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Servicios
    {
        public tbl_Servicios()
        {
            this.tbl_ConceptosServicios = new HashSet<tbl_ConceptosServicios>();
            this.tbl_PagosMantenciones = new HashSet<tbl_PagosMantenciones>();
            this.tbl_ServiciosAdquisicion = new HashSet<tbl_ServiciosAdquisicion>();
        }
    
        public int ID { get; set; }
        public string Servicio { get; set; }
        public bool IsActive { get; set; }
        public int CategoriaID { get; set; }
    
        public virtual tbl_Categorias tbl_Categorias { get; set; }
        public virtual ICollection<tbl_ConceptosServicios> tbl_ConceptosServicios { get; set; }
        public virtual ICollection<tbl_PagosMantenciones> tbl_PagosMantenciones { get; set; }
        public virtual ICollection<tbl_ServiciosAdquisicion> tbl_ServiciosAdquisicion { get; set; }
    }
}
