//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Causas
    {
        public tbl_Causas()
        {
            this.tbl_Difuntos = new HashSet<tbl_Difuntos>();
        }
    
        public int ID { get; set; }
        public string Causa { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<tbl_Difuntos> tbl_Difuntos { get; set; }
    }
}
