//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_HistorialAdquisicion
    {
        public int ID { get; set; }
        public int UsuarioID { get; set; }
        public int AdquisicionID { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public string Accion { get; set; }
    
        public virtual tbl_Adquisicion tbl_Adquisicion { get; set; }
        public virtual tbl_Usuarios tbl_Usuarios { get; set; }
    }
}
