//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Patios
    {
        public tbl_Patios()
        {
            this.tbl_Secciones = new HashSet<tbl_Secciones>();
        }
    
        public int ID { get; set; }
        public string Patio { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> CementerioID { get; set; }
    
        public virtual tbl_Cementerios tbl_Cementerios { get; set; }
        public virtual ICollection<tbl_Secciones> tbl_Secciones { get; set; }
    }
}
