//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestionador.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_PagoAdquisicion
    {
        public int ID { get; set; }
        public int FormaPagoID { get; set; }
        public int NroRecaudacion { get; set; }
        public decimal Monto { get; set; }
        public System.DateTime FechaRegistro { get; set; }
        public int UsuarioID { get; set; }
        public int AdquisicionID { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime FechaPago { get; set; }
        public string NroCheque { get; set; }
        public Nullable<int> BancoID { get; set; }
    
        public virtual tbl_Adquisicion tbl_Adquisicion { get; set; }
        public virtual tbl_Bancos tbl_Bancos { get; set; }
        public virtual tbl_FormasPago tbl_FormasPago { get; set; }
    }
}
