name: Deploy MVC Application via FTP

on:
  push:
    branches:
      - master
      - sanpedro

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: ${{ github.ref_name }}
    
    steps:              
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
  
      - name: Restore NuGet packages
        run: nuget restore ./GestionColegios.sln
  
      - name: Build and Publish solution
        run: msbuild ./GestionColegios.sln /p:Configuration=Release /t:Build /t:Publish /p:OutDir=${{ github.workspace }}/publish-output/
        
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ${{ github.workspace }}/publish-output/_PublishedWebsites/GestionColegios/
          server-dir: /gestioneducacional.cl/
